### ISSUE TITLE
Biraz Dökümantasyon ve Örnek

### ISSUE THREAD

**Issue by alpteko** [olcaytaner/TurkishMorphologicalAnalysis-Py#1]
Merhaba, elinize sağlık çok güzel bir tool yaratmışsınız. Machine Learning insanları olarak Türkçe ile uğraşmak bizim için zor oluyor eklerden dolayı. Ama bu kodu nasıl çalıştıracağız, ne hangi anlama geliyor (OA: özel isim vb) gibi şeyleri daha detaylı tanıtırsanız yanlış kullanmamış oluruz. İnsan aklına kolay yatana daha yatkın oluyor bu gibi durumlarda, yanlış çıkarımlar olabiliyor. 

Yeniden teşekküreler, iyi çalışmalar

**Comment by gokhanercan** [comment]
Merhaba, geri bildiriminiz için teşekkürler. Bu kütüphane aşağıda linkini verdiğim kütüphanenin Python uygulaması. Oradaki Java dökümantasyon giriş için işinize yarayabilir. https://github.com/olcaytaner/TurkishMorphologicalAnalysis

IS_OA gibi niteliklerin açıklamaları ve daha fazlası için kütüphanenin [makalesini ](https://www.aclweb.org/anthology/R19-1156.pdf)inceleyebilirsiniz. 
[An Open, Extendible, and Fast Turkish Morphological Analyzer](https://www.aclweb.org/anthology/R19-1156.pdf)

Aşağıya ilgili tabloyu ekliyorum. IS_OA örneğin özel isim demek. 
![image](https://user-images.githubusercontent.com/1479777/74532496-63421d80-4f40-11ea-9086-2b8c0a331f72.png)


İyi çalışmalar
